name: Lint

on: 
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Lint Python
          uses: psf/black@stable
          with:
            options: "--check --verbose"
            jupyter: true
            
