# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Nightly Tests
    runs-on: ubuntu-latest
    environment: development
    env:
      url: ${{ secrets.URL }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
    - name: Bootstrap Add-on
      run: |
        ./ao bootstrap --url "$url" --username "$username" --password "$password"
    - name: Deploy Add-on to Seeq Instance
      run: |
          ./ao deploy --clean
    - name: Test Add-on
      run: |
        ./ao test