name: Deploy Sphinx documentation to Pages

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # branch to trigger deployment
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Cancel any in-progress job or run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Build & Deploy Sphinx
      id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
        documentation_path: ./docs/source
