# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test & Deploy to Develop Channel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      url: ${{ secrets.URL }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Bootstrap Add-on
      run: |
        ./ao bootstrap --url "$url" --username "$username" --password "$password"
    - name: Test Add-on
      run: |
        ./ao test
    - name: Deploy Add-on to Seeq Instance
      run: |
        ./ao deploy --clean
